### ISSUE TITLE
android: C++ API/ABI compatibility with old Androids?

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#376]
Currently we build MK for Android using API level 21. However, previous NDKs and API levels use slightly different runtimes. For example, with @Lymphatus this evening we discovered that MK fails to run on an emulator running at API 19 becase symbol `__cmsg_nxthdr` (used by traceroute) is missing.

The precise error that happens is: `Java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cmsg_nxthdr" referenced by "libmeasurement_kit_jni.so"...`

This happens because, among the [release notes of NDK 10b](http://developer.android.com/ndk/downloads/revision_history.html) we read:

```
Android NDK, Revision 10b (September 2014) 
[...]
"Renamed cmsg_nxthdr to __cmsg_nxthdr."
```

How do we deal with this (and potentially similar issues)?

**Comment by lorenzoPrimi** [comment]
@bassosimone  searching on the web I got should be some compilation problem
https://github.com/libuv/libuv/issues/664

If we can't resolve it we will change the min API level, but I don't think we should do it.

**Comment by bassosimone** [comment]
I think that, if we use, say, API level 16, then the app would not work with new devices for the opposite reason. That is `cmsg_nxthdr() is missing`. Does it make sense?

**Comment by bassosimone** [comment]
To start addressing this issue I've implemented 08d67e2

**Comment by bassosimone** [comment]
Here is another test case. Running v.0.3.9-1 on Android 2.3.7 (API level 10), we get the following stack trace and the application does not run:

```
547-1547/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.ExceptionInInitializerError
                                                     at java.lang.Class.newInstanceImpl(Native Method)
                                                     at java.lang.Class.newInstance(Class.java:1409)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1021)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1561)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:117)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:130)
                                                     at android.app.ActivityThread.main(ActivityThread.java:3683)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:507)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1311]:  1130 cannot locate '__strlcpy_chk'...
                                                 
                                                     at java.lang.Runtime.loadLibrary(Runtime.java:434)
                                                     at java.lang.System.loadLibrary(System.java:554)
                                                     at org.openobservatory.ooniprobe.activity.MainActivity.<clinit>(MainActivity.java:48)
                                                     at java.lang.Class.newInstanceImpl(Native Method) 
                                                     at java.lang.Class.newInstance(Class.java:1409) 
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1021) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1561) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663) 
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:117) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:130) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:3683) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:507) 
```

**Comment by lorenzoPrimi** [comment]
Log on Android 4.2.2, API 17

```
12-07 13:52:22.599 2570-2570/org.openobservatory.ooniprobe E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_relocate(linker.cpp:987): cannot locate symbol "__strrchr_chk" referenced by "libmeasurement_kit.so"...
                                                                                 at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                                 at java.lang.System.loadLibrary(System.java:514)
                                                                                 at org.openobservatory.ooniprobe.activity.MainActivity.<clinit>(MainActivity.java:59)
                                                                                 at java.lang.Class.newInstanceImpl(Native Method)
                                                                                 at java.lang.Class.newInstance(Class.java:1319)
                                                                                 at android.app.Instrumentation.newActivity(Instrumentation.java:1057)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2260)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2412)
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:162)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5388)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bassosimone** [comment]
Okay, I've figured out it all. [Android C API and ABI was significantly changed with the introduction of API 21 and 64 bit architectures, while it basically was the same at least from API level 9](http://stackoverflow.com/a/27093163). What we should do is build for the earliest available platform given a NDK and an architecture (API level 9 for 32 bit architectures, API level 21 for the 64 bit ones).

Quickly hacking this, I was able to run [the example Android app](https://github.com/measurement-kit/android-example) compiled for API 14 on a MIPS simulator with API 16. So, yes, success, it should be possible to go down this road by targeting older headers. Roadmap:

- [ ] modify Android build system to use API 9/21 on 32/64 bit architectures
- [ ] fix issue in ndt/messages.cpp that [requires __STDC_LIMIT_MACROS defined](http://stackoverflow.com/a/986584)
- [ ] document that for API < 21 we link against a `arc4random_buf` not declared in headers
- [ ] re-enable traceroute on Android
- [ ] schedule more enhancements of the Android build system

All in all, I guess this part of work should be ready during beta.2 (i.e. two-three weeks from now).

**Comment by bassosimone** [comment]
I am now closing this issue. We have an open pull request (#1047) that address this issue, and therefore we don't need to *also* keep the issue open. Opened issues reduction FTW!

**Comment by bassosimone** [comment]
Reopening because there was a roadmap of subtasks to be performed before closing this issue. Umpf.
